### PR TITLE
Dockerize the development environment. 

### PR DESCRIPTION
**Pull request by doctoryes**
Dockerize the development environment. After these changes, you'll be able to run the the backend services with only Docker installed on your development machine. The advantages:
- No native install of Golang or MySQL needed.
- No snowflake servers - same standard development environment for all. Same versions of all dependencies.

 I've tested these changes on MacOS, Linux, and Windows 7 - Windows 7 didn't quite work due to volume path issues but MacOS and Linux worked fine. I encourage people to grab this branch and try it out themselves.

Other changes:
- Change README.txt to GitHub markdown.
- Relocate the Go code to a separate directory.
- Add a automated facility for populating the database initially via ```make init_db```.

@psiegel @psiegeldb @jonradoff FYI.

### CODE REVIEW

**Comment by psiegel** [comment]
Nice, I will check this out asap.  I've never used docker, so review may be slightly delayed as I figure out how to use it.

**Comment by doctoryes** [comment]
@psiegel @jonradoff I added a README file for the `docker` directory. Does it help explain things? How could I improve it?

**Comment by doctoryes** [comment]
BTW, using Docker also gives a good path to CI testing via Travis, which can spin up Docker containers and run tests in an identical environment for each pull request.

**Comment by doctoryes** [comment]
🎉 !

**Pull request merged**
